### ISSUE TITLE
打包之后没有action文件夹

### ISSUE THREAD

**Issue by qzp199510** [wsdo/taro-kit#1]
![c1e3ef7dde745a000e0343d8532bb0a](https://user-images.githubusercontent.com/39547706/46204141-bb2db380-c34e-11e8-965b-9a02014f5571.png)
![01ef5ab8f0b96cd2c675953caab45bf](https://user-images.githubusercontent.com/39547706/46204179-e3b5ad80-c34e-11e8-8ef2-edb58c270c86.png)

**Comment by wsdo** [comment]
![image](https://user-images.githubusercontent.com/9738969/46205592-cb945d00-c353-11e8-9877-18014b3daa52.png)
我打包后hen'jian很健康啊
