### ISSUE TITLE
请问下这种模式下如何判断接口调用结束

### ISSUE THREAD

**Issue by nslogx** [wsdo/taro-kit#3]
还望解答下，谢谢。。

**Comment by wsdo** [comment]
哪种模式？

**Comment by nslogx** [comment]
![image](https://user-images.githubusercontent.com/8692455/51085993-d85e8480-177b-11e9-8f64-e15cfc46002c.png)
比如说例子中的这个方法，我需要知道接口什么时候结束调用，新手不是很懂redux的流程。。

**Comment by wsdo** [comment]
那需要看看 redux 了  https://shudong.wang/about 有微信 可以在上面聊吧

**Comment by nslogx** [comment]
@wsdo 谢谢
